language: python
python:
  - "3.6" 
 
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE ahmad;" -U postgres

install: 
  - pip install -r requirements.txt


script:
  - pytest --cov 
  - coverage report

after_success:
- coveralls
